services:
  backend:
    build: ./back
    container_name: backend
    env_file:
      - ./back/.env
    restart: always
    ports:
      - "3000:3000"
    networks:
      - appnet

  frontend:
    build: ./front
    container_name: frontend
    restart: always
    networks:
      - appnet
    ports:
      - "80:80"

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    networks:
          - appnet
    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

networks:
  appnet:

volumes:
  mongodb-data:
